// Code generated by "stringer -linecomment -type CamMode"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AnyCam-0]
	_ = x[FirstPerson-1]
	_ = x[ThirdPersonBack-2]
	_ = x[ThirdPersonFront-3]
}

const _CamMode_name = "AnyCamFirstPersonThirdPersonBackThirdPersonFront"

var _CamMode_index = [...]uint8{0, 6, 17, 32, 48}

func (i CamMode) String() string {
	if i >= CamMode(len(_CamMode_index)-1) {
		return "CamMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CamMode_name[_CamMode_index[i]:_CamMode_index[i+1]]
}
