// Code generated by "stringer -linecomment -type ParticleSpawnerFlags"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttractorKill-1]
}

const _ParticleSpawnerFlags_name = "Particle dies on contact"

var _ParticleSpawnerFlags_index = [...]uint8{0, 24}

func (i ParticleSpawnerFlags) String() string {
	i -= 1
	if i >= ParticleSpawnerFlags(len(_ParticleSpawnerFlags_index)-1) {
		return "ParticleSpawnerFlags(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ParticleSpawnerFlags_name[_ParticleSpawnerFlags_index[i]:_ParticleSpawnerFlags_index[i+1]]
}
