// Code generated by "stringer -linecomment -type ParticleTextureFlags"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Animated-1]
}

const _ParticleTextureFlags_name = "Animated"

var _ParticleTextureFlags_index = [...]uint8{0, 8}

func (i ParticleTextureFlags) String() string {
	i -= 1
	if i >= ParticleTextureFlags(len(_ParticleTextureFlags_index)-1) {
		return "ParticleTextureFlags(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ParticleTextureFlags_name[_ParticleTextureFlags_index[i]:_ParticleTextureFlags_index[i+1]]
}
